version: "3.8"

services:
  app:
    build:
      context: .  
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - API_PORT=8080
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - db-net

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - db-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - db-net

networks:
  db-net:
