// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Business         string
	Shelter          string
	ShelterNeeds     string
	ShelterResidents string
	Volunteer        string
}{
	Business:         "business",
	Shelter:          "shelter",
	ShelterNeeds:     "shelter_needs",
	ShelterResidents: "shelter_residents",
	Volunteer:        "volunteer",
}
